
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Boxleague','com_boxleague.boxleague','{"special":{"dbtable":"#__boxleague_boxleague","key":"id","type":"Boxleague","prefix":"BoxleagueTable"}}', '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/boxleague.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_boxleague.boxleague')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Boxleague', 
	`table` = '{"special":{"dbtable":"#__boxleague_boxleague","key":"id","type":"Boxleague","prefix":"BoxleagueTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/boxleague.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_boxleague.boxleague');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Box','com_boxleague.box','{"special":{"dbtable":"#__boxleague_box","key":"id","type":"Box","prefix":"BoxleagueTable"}}', '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/box.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"boxleague_id","targetTable":"#__boxleague_boxleague","targetColumn":"id","displayColumn":"bl_name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_boxleague.box')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Box', 
	`table` = '{"special":{"dbtable":"#__boxleague_box","key":"id","type":"Box","prefix":"BoxleagueTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/box.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"boxleague_id","targetTable":"#__boxleague_boxleague","targetColumn":"id","displayColumn":"bl_name"}]}'
WHERE (`type_alias` = 'com_boxleague.box');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Player','com_boxleague.player','{"special":{"dbtable":"#__boxleague_player","key":"id","type":"Player","prefix":"BoxleagueTable"}}', '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/player.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"box_id","targetTable":"#__boxleague_box","targetColumn":"id","displayColumn":"boxleague_id"},{"sourceColumn":"user_id","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_boxleague.player')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Player', 
	`table` = '{"special":{"dbtable":"#__boxleague_player","key":"id","type":"Player","prefix":"BoxleagueTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/player.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"box_id","targetTable":"#__boxleague_box","targetColumn":"id","displayColumn":"boxleague_id"},{"sourceColumn":"user_id","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"}]}'
WHERE (`type_alias` = 'com_boxleague.player');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Match','com_boxleague.match','{"special":{"dbtable":"#__boxleague_match","key":"id","type":"Match","prefix":"BoxleagueTable"}}', '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/match.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"box_id","targetTable":"#__boxleague_box","targetColumn":"id","displayColumn":"boxleague_id"},{"sourceColumn":"home_player","targetTable":"#__boxleague_player","targetColumn":"id","displayColumn":"id"},{"sourceColumn":"away_player","targetTable":"#__boxleague_player","targetColumn":"id","displayColumn":"id"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_boxleague.match')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Match', 
	`table` = '{"special":{"dbtable":"#__boxleague_match","key":"id","type":"Match","prefix":"BoxleagueTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_boxleague\/models\/forms\/match.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"box_id","targetTable":"#__boxleague_box","targetColumn":"id","displayColumn":"boxleague_id"},{"sourceColumn":"home_player","targetTable":"#__boxleague_player","targetColumn":"id","displayColumn":"id"},{"sourceColumn":"away_player","targetTable":"#__boxleague_player","targetColumn":"id","displayColumn":"id"}]}'
WHERE (`type_alias` = 'com_boxleague.match');
